<a href='https://aims-senegal.org/'> <img src='http://sn.nexteinstein.org/wp-content/uploads/sites/12/2016/07/aims_senegal.jpg' /></a>

In [ ]:
# run this cell first
import numpy as np



---



---



---



# Exercise A:




### 1- Construct a Ndarray  of shape (3, 2) filled with **8**, Then set element (0, 1) to 10, and element (1, 0) to 100

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


A=np.array([[8,8],[8,8],[8,8]])
A
A[0,1]=10
A
A[1,0]=100
A
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[  8,  10],
       [100,   8],
       [  8,   8]])

### 2- Create a 64-bit floating-point Ndarray of shape (6,) (six-element vector) filled with evenly-spaced values between 10 and 20. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


B= np.array([10.,12.,14.,16.,18.])
B
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10., 12., 14., 16., 18.])

### 3- Create a vector with values ranging from 10 to 49

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

C=np.arange(0,50)
C
#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### 4- Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

D=np.arange(0,9).reshape(3,3)
D
#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5- Create a 10x10 array with random values and print the trace value and the mean values of each row

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

E= np.random.random((10,10))
#E
print('trace of E:' ,np.trace(E))

print("mean are:", np.mean(E,axis=1))

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

trace of E: 4.148427866223175
mean are: [0.6368182  0.49748147 0.63543687 0.56605807 0.48487104 0.40746587
 0.31520722 0.43676683 0.43379251 0.59077924]


### 6- Create a Ndarray array of size (5, 5) with all **1** on the borders and all **0** in the inside


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

F=np.ones((5,5))
F[1:-1,1:-1]=0
F
#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 7- Create random vector of size 10 and replace the maximum value by 0

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


G=np.random.random(10)
G
G[G.argmax()]=0
G
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([0.18206609, 0.50143434, 0.        , 0.83987777, 0.41158287,
       0.73165467, 0.54811184, 0.08702268, 0.46175005, 0.05952296])

### 8- Normalize a 5x5 random matrix
Hint: subtract the mean and devide by the standard deviation

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
I= np.random.randn(5,5) 

(I - I.mean())/np.sqrt(I.std())
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[ 0.17270262,  0.2767391 ,  0.82068609, -0.15450103,  0.0609364 ],
       [-1.88925065, -1.50508094, -2.23011401, -1.18581722, -0.18715493],
       [ 1.58849131,  0.99960708,  0.26978427,  0.58008668, -2.24740567],
       [ 0.60471047,  0.2970647 ,  0.66333914,  0.46347219,  0.69733965],
       [ 1.06118308, -1.23656335,  2.05989522, -0.16067084,  0.18052065]])

### 9- Create a random 5x2 matrix representing cartesian coordinates and print an array **"polar"** with same shape representing the converted polar coordinates.

Hints:

X represent the first column.

Y represent the second column.

Compute:

$$ R = \sqrt{X^2 + Y^2} $$

$$ T = \arctan{(Y, X)} $$


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
K=np.random.random((5,2))
K
K[:,1]
#K
R=np.sqrt((K[:,0])**2 + (K[:,1])**2)

T=np.arctan(K[:,0],K[:,1])
print(R)
print(T)


 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

[0.48035886 1.17609544 1.06501186 1.31511873 0.28193848]
[0.30929026 0.66850123 0.49685218 0.73644992 0.2505669 ]




---



---



---



### 10- Write a function that normalizes the columns of a matrix. It should compute the mean and standard deviation of each column, then subtract the mean and divide by the standard deviation for each element in the column. 

Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- The first column has mean 0 and std 1
- The second column has mean 20 and std 10
- The third column has mean 400 and std 200

After normalizing the columns, the result should be:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

Your implementation should not use any loops; instead you should use reduction and broadcasting operations.

In [ ]:


def normalize_columns(x):

  q=(x- np.mean(x,axis=0))/np.std(x,axis=0)
  return q



In [ ]:
x=  [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
normalize_columns(x)

array([[ 0.        ,  1.22474487,  1.22474487],
       [ 1.22474487, -1.22474487, -1.22474487],
       [-1.22474487,  0.        ,  0.        ]])

In [ ]:
x0 = np.array([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1.224744871391589, 1.224744871391589], [1.224744871391589, -1.224744871391589, -1.224744871391589], [-1.224744871391589, 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]

Here is x0:
[[  0.  30. 600.]
 [  1.  10. 200.]
 [ -1.  20. 400.]]
Here is y0:
[[ 0.          1.22474487  1.22474487]
 [ 1.22474487 -1.22474487 -1.22474487]
 [-1.22474487  0.          0.        ]]




---



---



---



### 11- creates a function that returns a matrix of **one-hot vectors** from a list of Python integers. A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are commonly used to represent categorical variables in machine learning models.

### For example, given a list `[1, 4, 3, 2]` of integers, your function should produce the tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

### Here the first row corresponds to the first element of the list: it has a one at index 1, and zeros at all other indices. The second row corresponds to the second element of the list: it has a one at index 4, and zeros at all other indices. The other rows follow the same pattern. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def make_one_hot(x):
 H = np.zeros((x.size, x.size+1))
 H[np.arange(x.size),x] = 1
 return H

  
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [ ]:
x=np.array([1,4,3,2])
make_one_hot(x)

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

Run the following cell to check your implementation, you must see 'all checks pass!' message

In [ ]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = np.array([1, 3, 5, 7, 6, 2])
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

AttributeError: ignored



---



---



---



# Exercise B:

### Maximum Likelihood
Find the maximum likelihood estimation of parameters $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N
$$

Steps to follow:


1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Compute the maximum likelihood estimation of parameters $\boldsymbol\theta$ following the equation and assign it to a variable called **theta**

$$
\boldsymbol\theta = (\boldsymbol X^T\boldsymbol X)^{-1}\boldsymbol X^T\boldsymbol y\in\mathbb{R}^D
$$

4. print the value of **theta**

Hint: check the inverse method from the linear algebra module in Numpy

In [ ]:
################################################################################
# TODO: Compute the maximum likelihood estimation of parameters theta
#       following the equation
################################################################################
X=np.random.randn(10,5)
y=np.ones(10).reshape(10,1)
theta=(np.linalg.inv(((X.T)@(X))))@X.T@y
print(theta)
#your code should be here

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

[[-0.50820658]
 [-0.4957879 ]
 [-0.06824076]
 [-0.18210727]
 [ 0.31196509]]




---



---



---



# Exercise B:

### The Log Likelihood

Find the log likelihood estimation for input X, label y, parameterized by $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N \quad \boldsymbol \theta  \in\mathbb{R}^D
$$

steps to follow:

1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Initialize Ndarray **theta** randomly with shape D = 5 and reshape it to have the shape (D, 1).
4.   Compute the the probability of a all data points $(\boldsymbol x, y)$ being of class 1, given by

$$p(y = 1 | \boldsymbol X, \boldsymbol\theta) = 1.0/(1.0+\exp(- \boldsymbol X \boldsymbol \theta))$$

5. compute the log Likelihood, given by:
$$\log p(\boldsymbol y|\boldsymbol X, \boldsymbol\theta) = \sum_i y_i * \log (p(y = 1 | \boldsymbol x, \boldsymbol\theta) + (1 - y_i) * \log ( 1 - p(y = 1 | \boldsymbol x, \boldsymbol\theta))$$

6. print the log Likelihood

In [ ]:
################################################################################
# TODO: Compute the log likelihood 
#    
################################################################################


#your code should be here

X = np.random.randn(10, 5)
y = np.ones((10,1))
theta = np.random.random((5, 1))

p = 1.0/(1 + np.exp(-X @ theta))
LOG_p = np.sum(y*np.log(p) + (1 - y)*np.log(1 - p))

print(LOG_p)
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

-5.8491831776782615
