### Data structures - Day 2

* Stacks
* Queues
* Linked List

## Revision on Lists, Tuples, Sets, Dictionary

### List
* Creating lists
* Indexing lists
* Inerting and removing items
* Item assignment
* Extending 
* Concatenation
* Searching items
* Iteration



In [ ]:
l = [2, 4, 6]
del l[0]


### Tuple
* Creating tuples
* Indexing tuples
* Searching items
* Iteration




In [ ]:
t = tuple([4, 6,7])

In [ ]:
del t[0]

TypeError: ignored


### Sets
* Creating sets
* Adding and removing items
* Union 
* Intersection
* Searching items
* Iteration
* Possible items data type

In [ ]:
s = set([6, 7, (7, 9)])
# s[0]

In [ ]:
l = [5, 6]

In [ ]:
l.append(6)
l

[5, 6, 6]

In [ ]:
s = set((3, 5, 6))
s = set("abcd")

In [ ]:
s = set([3, 5, 6, [5, 6]])

s = {3, 5, 6}

In [ ]:
s = {4, 6, 8, 8}

In [ ]:
l = (5, 6)
s1 = {l}

### Dictionary


In [ ]:
a = {i:2 * i for i in range(10)}

In [ ]:
a

{0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18}

In [ ]:
for key in a:
  print(key)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# for key, value in a.items():
#   print("key: {} value: {}".format(key, value))


for index, (key, value) in enumerate(a.items()):
  print("index:{} key: {} value: {}".format(index, key, value))

index:0 key: 0 value: 0
index:1 key: 1 value: 2
index:2 key: 2 value: 4
index:3 key: 3 value: 6
index:4 key: 4 value: 8
index:5 key: 5 value: 10
index:6 key: 6 value: 12
index:7 key: 7 value: 14
index:8 key: 8 value: 16
index:9 key: 9 value: 18


## Linked Lists

* Another implementation of List ADT
* Each element has reference to next element(which could be None for tail)
* Have two properties, head node and tail node


<img src="https://upload.wikimedia.org/wikipedia/commons/b/bf/Linked_list_data_format.jpg"/><br/>
<b>fig src:[https://upload.wikimedia.org/wikipedia/commons/b/bf/Linked_list_data_format.jpg](https://upload.wikimedia.org/wikipedia/commons/b/bf/Linked_list_data_format.jpg)</b>

### Linked List - Node
* Is each element in linked list
* Has two properties
  * Data
  * Next 

  
### Implementing Linked List


In [ ]:
## Node contains two attributes
## * data => could be number type or string  
## * next => reference to next element, can be None

class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

In [ ]:
node = Node(28)

### Practice Question 1

Implement node for linked list(Singly linked list)

In [ ]:
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

In [ ]:
node = Node("Africa")

In [ ]:
node

## Practice Question 2
Implement linked list class


In [ ]:

class LinkedList:
  def __init__(self):
    self.head = None
    self.tail = None
  def insert_at_start(self, data):
    # data is integer
    # You need to create a node with this data
    
    node = Node(data)
    # Case 1: There are no elements
    if self.head is None:
      self.head = self.tail = node
    else:
      node.next = self.head
      self.head = node
  def insert(self, data, index):
    

  def insert_at_end(self, data):
    pass
  def display(self):
    pass
  def search(self, data): 
    # Return the index of first occurance of a data. 
    # if the data is not found return -1
    current = self.head
    i = 0
    while current is not None:
      if current.data == data:
        return i
      current = current.next
      i += 1
    return -1

  def delete(self, data): 
    # Delete only the first occurance
    pass
  

In [ ]:
l = [20, 12, 2, 13, 1]
linked_list = LinkedList()
for i in l[::-1]:
  linked_list.insert_at_start(i)

In [ ]:
current = linked_list.head
i = 0
while current is not None:
  current = current.next
  i += 1

index '0'  element is '20' 
index '1'  element is '12' 
index '2'  element is '2' 
index '3'  element is '13' 
index '4'  element is '1' 


In [ ]:
ll = LinkedList()

In [ ]:
class DNode:
  def __init__(self, data):
    self.prevous = None
    self.next = None
    self.data = data

In [ ]:
ll.insert_at_end(10)
ll.insert_at_end(1)
ll.insert_at_start(20)
ll.insert_at_end(9)
ll.insert_at_start(2)

In [ ]:
ll.display()

2=>20=>10=>1=>9


## Doubly Linked List
* A linked List where each node is connected two other nodes
* It is possible to traverse from tail to head as well as from head to tail.

## Practice Question 3
Implement Doubly Linked List

In [ ]:
class DNode:
  pass
class DLinkedList:
  def __int__(self):
    pass
  def insert_at_start(self, data):
    pass
  def insert(self, data, index):
    pass
  def insert_at_end(self, data):
    pass
  def display(self):
    pass
  def search(self, data):
    pass
  def delete(self, data): # Delete only the first occurance
    pass

### Practice Question 4
* Implement a function which that accepts a sentence(word) and create Doubly Linked List, where each node coresponds to each characters in the sentence(word)
* Create another function which accepts the doubly linked list above and checks if the sentence is palyndrome or not.

## Stacks

* Stacks are abstract datatypes. 
* Python doesn't provide stack builtin implementations
* Last In First Out ADT
* Have the following operations
  * Push: adds an element on top of the stack
  * Pop: removes an element from the top of the stack<br/>
  * empty: Checks if the stack is empty
  <b>Optionally</b>
  * Peek: To see the top elements
  * Size: Retrieves the number of elements of the stack




### Implementing stacks with list
* `append()` method of list for push operation
* `pop()` method of list for pop operation
* indexing with last index for peek operation
* list.__len__() == 0 for empty operation 
* list.__len__() for size operation


In [ ]:
class Stack:
  def __init__(self):
    self.__collection = list()
  def push(self, element):
    self.__collection.append(element)
  def pop(self):
    if self.empty():
      return None
    return self.__collection.pop()
  def empty(self):
    return len(self.__collection) == 0
  def peek(self):
    if self.empty():
      return None
    return self.__collection[len(self.__collection) - 1]


6

In [ ]:
l

[4]

In [ ]:
stack = list()
stack.append("one") # Push operation
element = stack.pop() # Pop operation
print("element", element)
print("Is empty: ", len(stack)==0) # Empty operation
print("Size", len(stack))

## Practice question 5
* Implement Stack class

In [ ]:
class Stack(object):
  def __init__(self):
    pass
  def push(self, element):
    pass
  def pop(self):
    pass
  def empty(self):
    pass
  def size(self):
    return pass

## Example Reverse words in Sentence

## Checking for valid bracket matching

```python
isValid("{{()}}")  # True
isValid("{{(})}")  # False
isValid("{}")  # True


```

In [ ]:
stack = Stack()

In [ ]:
dir(stack)

In [ ]:
stack.push(1)
stack.push(2)
stack.push(3)
print(stack.pop())
stack.push(4)
stack.push(5)
print(stack.pop())


In [ ]:
stack.pop()

In [ ]:
stack.pop()

In [ ]:
stack.pop()

## Queues
* Similar to stack
* First In First Out(FIFO) ADT
* Python provides [deque objects](https://docs.python.org/3/library/collections.html#collections.defaultdict), to implement queue



**We** will implement Queue the same way as we implemented Stack. But here we will use deque to instead of list. Deque are more effient[O(1)] to add item to the start index compared with list which requires  O(n) time complexity to add item to the start index.

Queues can be implemented in different ways. For simplicty we will use lists to implement Queues. Note that removing an element from front(start index) is O(n). So this implementation is not efficient as other implementation you might find. One efficient way to implement queue is using deque. This data-structures are optimized to remove and add items from both ends.


In [ ]:
class Queue:

  def __init__(self):
    self.__collection = list()
  def enque(self, item):
    self.__collection.append(item)
  def deque(self):
    item = self.__collection[0]
    self.__collection = self.__collection[1:]
    return item
  def empty(self):
    return self.size() == 0
  def size(self):
    return len(self.__collection)
    

## Operator Over loading

Follow [here](https://docs.python.org/3/library/operator.html)

### Practice Question Implementing Vector Data structure


* Create a class Vector to Rerpresent vectors in Vector space
* The class's initializer should accept a list containing numbers
* Vector has the following attributes
  * elements # List of numbers
  * dim # The dimension of the vector
* Multiplication by scalar(Implement right side scalar multiplication as follows)
  $$V * a
  $$
* Dot product ( Use @ as dot product operator)
  $$\mathbf{x}@\mathbf{y}$$
* Addition/subtraction
* method called `norm()` to get the l2 norm of the vector

In [ ]:
import numpy as np
class Vector:
  def __init__(self,vector):
    self.vector=np.array(vector)
  def __mul__(self,a):
    mul=self.vector*a
    return mul
  def __matmul__(self,other):
    return self.vector@other.vector
  def __add__(self,other):
    return self.vector + other.vector
  def __sub__(self,other):
    return self.vector - other.vector
  def norm(self):
    return np.sum((self.vector)**0.5)

In [ ]:
vector=Vector([1,2,3])
a=2
print(Vector.__mul__(vector,2))
b=Vector([2,3,4])
print(Vector.__matmul__(vector,b))
print(Vector.__add__(vector,b))
print(Vector.__sub__(vector,b))
print(Vector.norm(vector))



[2 4 6]
20
[3 5 7]
[-1 -1 -1]
4.146264369941973


### Practice Question: Implementing Matrix datastructure

* Create a class Matrix to Rerpresent Matrix objects
* The class's initializer should accept a nested list containing numbers
* Vector has the following attributes
  * elements(List of List of numbers)
  * shape # The dimensions of the matrix
* Multiplication by scalar(Implement right side scalar multiplication as follows)
  $$V * a
  $$
* The Matrix multiplication should work with vectors also
* Matrix multiplication ( Use @ as matrix maltiplication operator)
  $$\mathbf{x}@\mathbf{y}$$
  
* Addition/subtraction
* method called `norm()` to get the Frobenius norm of the matrix
* method called `transpose()` to get the transpose of a matrix
* method called `trace()` to get the trace of the matrix












In [ ]:
import numpy as np
class Matrix:
  def __init__(self,matrix):
    self.matrix=np.array(matrix)
  def __mul__(self,a):
    mul=self.matrix*a
    return mul
  def __matmul__(self,other):
    return self.matrix*other.matrix
  def __add__(self,other):
    return self.matrix + other.matrix
  def __sub__(self,other):
    return self.matrix - other.matrix
  def norm(self):
    return np.sum((self.matrix)**0.5)
  def norm(self):
    return np.sum((self.matrix)**0.5)
  def norm(self):
    return np.sum((self.matrix)**0.5)

In [ ]:
matrix=Matrix([[1,2,3],[2,4,5]])
a=2
print(Matrix.__mul__(matrix,2))
c=Matrix([[2,3,4],[5,6,7]])
print(Matrix.__matmul__(matrix,c))
print(Matrix.__add__(matrix,c))
print(Matrix.__sub__(matrix,c))
print(Matrix.norm(matrix))
print(Matrix.norm(matrix))
print(Matrix.norm(matrix))



[[ 2  4  6]
 [ 4  8 10]]
[[ 2  6 12]
 [10 24 35]]
[[ 3  5  7]
 [ 7 10 12]]
[[-1 -1 -1]
 [-3 -2 -2]]
9.796545909814856


In [ ]:
class Point2D:
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def __repr__(self):
    return ("Point({}, {})".format(self.x, self.y))
  def __str__(self):
    return repr(self)
  def __add__(self, other):
    x = self.x + other.x
    y = self.y + other.y
    return Point2D(x, y)


  

In [ ]:
point = Point2D(3, 10.8)
print(point)

Point(3, 10.8)


In [ ]:
p2 = Point2D(10, 27)


In [ ]:
point + p2

Point(13, 37.8)

In [ ]:
class Vector:
  def __init__(self, vector):
    self.vector = vector
    
  def __mul__(self, a):
    l=list()
    for i in self.vector:
      l.append(a*i)
    return l
  def __matmul__(self,other):
    s=0
    for i in range(len(self.vector)):
      s+=self.vector[i]*other.vector[i]
    return s
  def __add__(self,other):
    m=list()
    for i,j in (zip(self.vector,other.vector)):
      k=i+j
      m.append(k)
    return m
  def norm (self):
    s=0
    for i in range(len(self.vector)):
      s+=self.vector[i]**2

    return s**0.5



In [ ]:
vector=Vector([1,2,3])
a=2
vector*a

[2, 4, 6]

In [ ]:
vector=Vector([1,2,3])
vector1=Vector([3,5,6])
vector@vector1

31

In [ ]:
vector + vector1

[4, 7, 9]

In [ ]:
vector.norm()

3.7416573867739413

In [ ]:
class Matrix:
  def __init__(self, matrix):
    self.matrix=np.array(matrix)
    
    #self.dim=dim
  def __mul__(self, a):
    l=list()
    for i in self.matrix:
           l.append(i*a)
    return l
  def __matmul__(self,other):
    s=0
    for i in range(len(self.vector)):
      s+=self.vector[i]*other.vector[i]
    return s
  def __add__(self,other):
    m=list()
    for i,j in (zip(self.vector,other.vector)):
      k=i+j
      m.append(k)
    return m
  def norm (self):
    s=0
    for i in range(len(self.vector)):
      s+=self.vector[i]**2

    return s**0.5



In [ ]:
np.arange

<function numpy.arange>

In [ ]:
matrix=Matrix([[1,2],[3,4]])

Matrix.__mul__(matrix,2)

[array([2, 4]), array([6, 8])]

In [ ]:
matrix2=[[1,4],[6,7]]

In [ ]:
matrix@matrix2

TypeError: ignored